version: '3'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
  server:
    container_name: server
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    build:
      context: ./server
  client_web:
    environment:
      - FRONT_PORT=8081
    volumes:
      - mobile_apk:/apk/
    container_name: client_web
    restart: always
    ports:
      - 8081:8081
    build:
      context: ./client
  mobile_client:
    volumes:
      - mobile_apk:/apk/
    container_name: mobile_client
    build:
      context: ./mobile_client

volumes:
  mobile_apk: